name: Clone and Push to Folder with Git LFS

on:
  workflow_dispatch:

jobs:
  clone_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install

    - name: Clone Hugging Face Repository
      run: git clone https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B

    - name: Move content into model_02 folder
      run: |
        mkdir -p model_02
        mv DeepSeek-R1-Distill-Qwen-32B/* model_02/
        rm -rf DeepSeek-R1-Distill-Qwen-32B  # Clean up the original folder

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Authenticate with Hugging Face
      run: echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

    - name: Push to New Hugging Face Repository
      run: |
        git init
        git add model_02
        git commit -m "Push model_02 to Hugging Face repository"
        git remote add origin https://huggingface.co/OpenDeca/2-mini
        git branch -M main
        git push -u origin main
